//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class adolescente
    {
        public string v_AdolescenteId { get; set; }
        public string v_PersonId { get; set; }
        public string v_EdadInicioTrabajo { get; set; }
        public string v_TipoTrabajo { get; set; }
        public string v_NroHorasTv { get; set; }
        public string v_NroHorasJuegos { get; set; }
        public string v_MenarquiaEspermarquia { get; set; }
        public string v_EdadInicioRS { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_NombreCuidador { get; set; }
        public string v_EdadCuidador { get; set; }
        public string v_DniCuidador { get; set; }
        public string v_ViveCon { get; set; }
        public string v_Observaciones { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual person person { get; set; }
    }
}
