//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlergiasInmunizaciones
    {
        public string v_AntecedentesId { get; set; }
        public string v_PersonaId { get; set; }
        public Nullable<bool> b_Alergias { get; set; }
        public Nullable<int> i_Ninfluenza { get; set; }
        public Nullable<int> i_NHepatitis { get; set; }
        public Nullable<int> i_Ntetano { get; set; }
        public Nullable<int> i_NFiebreAmarilla { get; set; }
        public Nullable<System.DateTime> d_FechaInsercion { get; set; }
        public Nullable<int> i_UsuarioInsertaId { get; set; }
        public Nullable<System.DateTime> d_FechaActualizacion { get; set; }
        public Nullable<int> i_UsuarioActualizaId { get; set; }
        public Nullable<bool> i_EsEliminado { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
