//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class applicationhierarchy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public applicationhierarchy()
        {
            this.protocolsystemuser = new HashSet<protocolsystemuser>();
            this.systemusergobalprofile = new HashSet<systemusergobalprofile>();
            this.rolenodeprofile = new HashSet<rolenodeprofile>();
        }
    
        public int i_ApplicationHierarchyId { get; set; }
        public Nullable<int> i_ApplicationHierarchyTypeId { get; set; }
        public Nullable<int> i_Level { get; set; }
        public string v_Description { get; set; }
        public string v_Form { get; set; }
        public string v_Code { get; set; }
        public Nullable<int> i_ParentId { get; set; }
        public Nullable<int> i_ScopeId { get; set; }
        public Nullable<int> i_TypeFormId { get; set; }
        public Nullable<int> i_ExternalUserFunctionalityTypeId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<protocolsystemuser> protocolsystemuser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<systemusergobalprofile> systemusergobalprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rolenodeprofile> rolenodeprofile { get; set; }
    }
}
