//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audiometria
    {
        public string v_AudiometriaId { get; set; }
        public string v_ServicioId { get; set; }
        public string v_Calibracion { get; set; }
        public string v_OtoscopiaOD { get; set; }
        public string v_OtoscopiaOI { get; set; }
        public string v_VAOD125 { get; set; }
        public string v_VAOD250 { get; set; }
        public string v_VAOD500 { get; set; }
        public string v_VAOD1000 { get; set; }
        public string v_VAOD2000 { get; set; }
        public string v_VAOD3000 { get; set; }
        public string v_VAOD4000 { get; set; }
        public string v_VAOD6000 { get; set; }
        public string v_VAOD8000 { get; set; }
        public string v_VAOI125 { get; set; }
        public string v_VAOI250 { get; set; }
        public string v_VAOI500 { get; set; }
        public string v_VAOI1000 { get; set; }
        public string v_VAOI2000 { get; set; }
        public string v_VAOI3000 { get; set; }
        public string v_VAOI4000 { get; set; }
        public string v_VAOI6000 { get; set; }
        public string v_VAOI8000 { get; set; }
        public string v_VOOD125 { get; set; }
        public string v_VOOD250 { get; set; }
        public string v_VOOD500 { get; set; }
        public string v_VOOD1000 { get; set; }
        public string v_VOOD2000 { get; set; }
        public string v_VOOD3000 { get; set; }
        public string v_VOOD4000 { get; set; }
        public string v_VOOD6000 { get; set; }
        public string v_VOOD8000 { get; set; }
        public string v_VOOI125 { get; set; }
        public string v_VOOI250 { get; set; }
        public string v_VOOI500 { get; set; }
        public string v_VOOI1000 { get; set; }
        public string v_VOOI2000 { get; set; }
        public string v_VOOI3000 { get; set; }
        public string v_VOOI4000 { get; set; }
        public string v_VOOI6000 { get; set; }
        public string v_VOOI8000 { get; set; }
        public string v_EM_A_OD125 { get; set; }
        public string v_EM_A_OD250 { get; set; }
        public string v_EM_A_OD500 { get; set; }
        public string v_EM_A_OD1000 { get; set; }
        public string v_EM_A_OD2000 { get; set; }
        public string v_EM_A_OD3000 { get; set; }
        public string v_EM_A_OD4000 { get; set; }
        public string v_EM_A_OD6000 { get; set; }
        public string v_EM_A_OD8000 { get; set; }
        public string v_EM_A_OI125 { get; set; }
        public string v_EM_A_OI250 { get; set; }
        public string v_EM_A_OI500 { get; set; }
        public string v_EM_A_OI1000 { get; set; }
        public string v_EM_A_OI2000 { get; set; }
        public string v_EM_A_OI3000 { get; set; }
        public string v_EM_A_OI_4000 { get; set; }
        public string v_EM_A_OI6000 { get; set; }
        public string v_EM_A_OI8000 { get; set; }
        public string v_EM_O_OD125 { get; set; }
        public string v_EM_O_OD250 { get; set; }
        public string v_EM_O_OD500 { get; set; }
        public string v_EM_O_OD1000 { get; set; }
        public string v_EM_O_OD2000 { get; set; }
        public string v_EM_O_OD3000 { get; set; }
        public string v_EM_O_OD4000 { get; set; }
        public string v_EM_O_OD6000 { get; set; }
        public string v_EM_O_OD8000 { get; set; }
        public string v_EM_O_OI125 { get; set; }
        public string v_EM_O_OI250 { get; set; }
        public string v_EM_O_OI500 { get; set; }
        public string v_EM_O_OI1000 { get; set; }
        public string v_EM_O_OI2000 { get; set; }
        public string v_EM_O_OI3000 { get; set; }
        public string v_EM_O_OI4000 { get; set; }
        public string v_EM_O_OI6000 { get; set; }
        public string v_EM_O_OI8000 { get; set; }
        public string v_ConclusionesAudiometria { get; set; }
        public Nullable<System.DateTime> d_FechaInsercion { get; set; }
        public Nullable<int> i_UsuarioInsertaId { get; set; }
        public Nullable<System.DateTime> d_FechaActualizacion { get; set; }
        public Nullable<int> i_UsuarioActualizaId { get; set; }
        public Nullable<bool> i_EsEliminado { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
