//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class calendar
    {
        public string v_CalendarId { get; set; }
        public string v_PersonId { get; set; }
        public string v_ServiceId { get; set; }
        public Nullable<System.DateTime> d_DateTimeCalendar { get; set; }
        public Nullable<System.DateTime> d_CircuitStartDate { get; set; }
        public Nullable<System.DateTime> d_EntryTimeCM { get; set; }
        public Nullable<int> i_ServiceTypeId { get; set; }
        public Nullable<int> i_CalendarStatusId { get; set; }
        public Nullable<int> i_ServiceId { get; set; }
        public string v_ProtocolId { get; set; }
        public Nullable<int> i_NewContinuationId { get; set; }
        public Nullable<int> i_LineStatusId { get; set; }
        public Nullable<int> i_IsVipId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<System.DateTime> d_SalidaCM { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual person person { get; set; }
        public virtual service service { get; set; }
    }
}
