//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class component
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public component()
        {
            this.attentioninareacomponent = new HashSet<attentioninareacomponent>();
            this.auxiliaryexam = new HashSet<auxiliaryexam>();
            this.componentfields = new HashSet<componentfields>();
            this.protocolcomponent = new HashSet<protocolcomponent>();
            this.recommendation = new HashSet<recommendation>();
            this.restriction = new HashSet<restriction>();
            this.rolenodecomponentprofile = new HashSet<rolenodecomponentprofile>();
            this.servicecomponent = new HashSet<servicecomponent>();
        }
    
        public string v_ComponentId { get; set; }
        public string v_Name { get; set; }
        public Nullable<int> i_CategoryId { get; set; }
        public Nullable<float> r_BasePrice { get; set; }
        public Nullable<int> i_DiagnosableId { get; set; }
        public Nullable<int> i_IsApprovedId { get; set; }
        public Nullable<int> i_ComponentTypeId { get; set; }
        public Nullable<int> i_UIIsVisibleId { get; set; }
        public Nullable<int> i_UIIndex { get; set; }
        public Nullable<int> i_ValidInDays { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_IdUnidadProductiva { get; set; }
        public Nullable<float> r_PriceSegus { get; set; }
        public string v_CodigoSegus { get; set; }
        public Nullable<int> i_GroupId { get; set; }
        public Nullable<int> i_SubGroupId { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public Nullable<int> i_KindOfService { get; set; }
        public Nullable<int> i_PriceIsRecharged { get; set; }
        public Nullable<int> i_DeduciblePay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attentioninareacomponent> attentioninareacomponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auxiliaryexam> auxiliaryexam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<componentfields> componentfields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<protocolcomponent> protocolcomponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recommendation> recommendation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restriction> restriction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rolenodecomponentprofile> rolenodecomponentprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicecomponent> servicecomponent { get; set; }
    }
}
