//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class componentfieldvalues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public componentfieldvalues()
        {
            this.componentfieldvaluesrecommendation = new HashSet<componentfieldvaluesrecommendation>();
            this.componentfieldvaluesrestriction = new HashSet<componentfieldvaluesrestriction>();
            this.servicecomponentfieldvalues = new HashSet<servicecomponentfieldvalues>();
        }
    
        public string v_ComponentFieldValuesId { get; set; }
        public string v_DiseasesId { get; set; }
        public string v_ComponentFieldId { get; set; }
        public string v_AnalyzingValue1 { get; set; }
        public string v_AnalyzingValue2 { get; set; }
        public Nullable<int> i_OperatorId { get; set; }
        public string v_LegalStandard { get; set; }
        public Nullable<int> i_IsAnormal { get; set; }
        public Nullable<int> i_ValidationMonths { get; set; }
        public Nullable<int> i_GenderId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual componentfield componentfield { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<componentfieldvaluesrecommendation> componentfieldvaluesrecommendation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<componentfieldvaluesrestriction> componentfieldvaluesrestriction { get; set; }
        public virtual diseases diseases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicecomponentfieldvalues> servicecomponentfieldvalues { get; set; }
    }
}
