//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionOc
    {
        public string i_CotizacionIdOc { get; set; }
        public string i_EmpresaId { get; set; }
        public string i_PersonId { get; set; }
        public string v_Description { get; set; }
        public string v_Comentary { get; set; }
        public Nullable<int> i_NumberOfWorker { get; set; }
        public Nullable<float> r_TotalCost { get; set; }
        public Nullable<System.DateTime> d_DeliveryDate { get; set; }
        public Nullable<int> i_LineaCreditoId { get; set; }
        public Nullable<int> i_EMOType { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public Nullable<int> i_MostrarPrecio { get; set; }
        public string v_RazonSocial { get; set; }
        public string v_RepresentanteLegal { get; set; }
        public string v_DireccionEmpresa { get; set; }
        public string v_Sumilla { get; set; }
        public string v_Asunto { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public string v_Interconsultas { get; set; }
        public string v_Anotaciones { get; set; }
    }
}
