//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion
    {
        public string v_CotizacionId { get; set; }
        public string v_PersonId { get; set; }
        public string v_ProtocolId { get; set; }
        public Nullable<decimal> d_CostoTotal { get; set; }
        public Nullable<decimal> d_aCuenta { get; set; }
        public Nullable<decimal> d_Saldo { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_Procesado { get; set; }
    }
}
