//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class deploymentfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public deploymentfile()
        {
            this.softwarecomponentrelease = new HashSet<softwarecomponentrelease>();
        }
    
        public int i_DeploymentFileId { get; set; }
        public string v_FileName { get; set; }
        public byte[] b_FileData { get; set; }
        public string v_Description { get; set; }
        public Nullable<int> i_SoftwareComponentId { get; set; }
        public string v_TargetSoftwareComponentVersion { get; set; }
        public string v_PackageFiles { get; set; }
        public Nullable<float> r_PackageSizeKb { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<softwarecomponentrelease> softwarecomponentrelease { get; set; }
    }
}
