//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class diagnosticrepository
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public diagnosticrepository()
        {
            this.recommendation = new HashSet<recommendation>();
            this.restriction = new HashSet<restriction>();
        }
    
        public string v_DiagnosticRepositoryId { get; set; }
        public string v_ServiceId { get; set; }
        public string v_DiseasesId { get; set; }
        public string v_ComponentId { get; set; }
        public string v_ComponentFieldId { get; set; }
        public Nullable<int> i_AutoManualId { get; set; }
        public Nullable<int> i_PreQualificationId { get; set; }
        public Nullable<int> i_FinalQualificationId { get; set; }
        public Nullable<int> i_DiagnosticTypeId { get; set; }
        public Nullable<int> i_IsSentToAntecedent { get; set; }
        public Nullable<System.DateTime> d_ExpirationDateDiagnostic { get; set; }
        public Nullable<int> i_GenerateMedicalBreak { get; set; }
        public string v_Recomendations { get; set; }
        public Nullable<int> i_DiagnosticSourceId { get; set; }
        public Nullable<int> i_ShapeAccidentId { get; set; }
        public Nullable<int> i_BodyPartId { get; set; }
        public Nullable<int> i_ClassificationOfWorkAccidentId { get; set; }
        public Nullable<int> i_RiskFactorId { get; set; }
        public Nullable<int> i_ClassificationOfWorkdiseaseId { get; set; }
        public Nullable<int> i_SendToInterconsultationId { get; set; }
        public Nullable<int> i_InterconsultationDestinationId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_InterconsultationDestinationId { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual componentfields componentfields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recommendation> recommendation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<restriction> restriction { get; set; }
        public virtual diseases diseases { get; set; }
        public virtual service service { get; set; }
    }
}
