//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class especiality
    {
        public string v_EspecialityId { get; set; }
        public string v_EspecialityName { get; set; }
        public byte[] b_EspecialityPicture { get; set; }
        public Nullable<System.TimeSpan> t_TimeForAttention { get; set; }
        public Nullable<decimal> r_Cost { get; set; }
        public string v_Description { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<System.TimeSpan> t_StartTime { get; set; }
        public Nullable<System.TimeSpan> t_EndTime { get; set; }
        public Nullable<System.TimeSpan> t_StartTime2 { get; set; }
        public Nullable<System.TimeSpan> t_EndTime2 { get; set; }
        public string v_ProtocolId { get; set; }
    }
}
