//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturacion()
        {
            this.facturaciondetalle = new HashSet<facturaciondetalle>();
        }
    
        public string v_FacturacionId { get; set; }
        public Nullable<System.DateTime> d_FechaRegistro { get; set; }
        public Nullable<System.DateTime> d_FechaCobro { get; set; }
        public string v_NumeroFactura { get; set; }
        public Nullable<int> i_EstadoFacturacion { get; set; }
        public string v_EmpresaCliente { get; set; }
        public string v_EmpresaSede { get; set; }
        public Nullable<decimal> d_Detraccion { get; set; }
        public Nullable<decimal> d_SubTotal { get; set; }
        public Nullable<decimal> d_Igv { get; set; }
        public Nullable<decimal> d_MontoTotal { get; set; }
        public Nullable<System.DateTime> d_FechaInicio { get; set; }
        public Nullable<System.DateTime> d_FechaFin { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_Descripcion { get; set; }
        public Nullable<decimal> d_Descuento { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facturaciondetalle> facturaciondetalle { get; set; }
    }
}
