//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class holidays
    {
        public string v_HolidayId { get; set; }
        public Nullable<int> i_Year { get; set; }
        public Nullable<System.DateTime> d_Date { get; set; }
        public string v_Reason { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
    }
}
