//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public int IdHorario { get; set; }
        public Nullable<int> i_SystemUserId { get; set; }
        public Nullable<System.DateTime> d_FechaInicio { get; set; }
        public Nullable<System.DateTime> d_FechaFin { get; set; }
        public Nullable<int> i_01 { get; set; }
        public Nullable<int> i_02 { get; set; }
        public Nullable<int> i_03 { get; set; }
        public Nullable<int> i_04 { get; set; }
        public Nullable<int> i_05 { get; set; }
        public Nullable<int> i_06 { get; set; }
        public Nullable<int> i_07 { get; set; }
        public Nullable<int> i_08 { get; set; }
        public Nullable<int> i_09 { get; set; }
        public Nullable<int> i_10 { get; set; }
        public Nullable<int> i_11 { get; set; }
        public Nullable<int> i_12 { get; set; }
        public Nullable<int> i_13 { get; set; }
        public Nullable<int> i_14 { get; set; }
        public Nullable<int> i_15 { get; set; }
        public Nullable<int> i_16 { get; set; }
        public Nullable<int> i_17 { get; set; }
        public Nullable<int> i_18 { get; set; }
        public Nullable<int> i_19 { get; set; }
        public Nullable<int> i_20 { get; set; }
        public Nullable<int> i_21 { get; set; }
        public Nullable<int> i_22 { get; set; }
        public Nullable<int> i_23 { get; set; }
        public Nullable<int> i_24 { get; set; }
        public Nullable<int> i_25 { get; set; }
        public Nullable<int> i_26 { get; set; }
        public Nullable<int> i_27 { get; set; }
        public Nullable<int> i_28 { get; set; }
        public Nullable<int> i_29 { get; set; }
        public Nullable<int> i_30 { get; set; }
        public Nullable<int> i_31 { get; set; }
        public string v_Comentary { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
    }
}
