//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospitalizacionEpicrisis
    {
        public string v_HospEpicrisisId { get; set; }
        public string v_HopitalizacionId { get; set; }
        public string v_Anamnesis { get; set; }
        public string v_ExamFisico { get; set; }
        public string v_ExamAuxiliares { get; set; }
        public string v_PlanTerapeutica { get; set; }
        public string v_IntervenvionesQx { get; set; }
        public string v_Evolucion { get; set; }
        public string v_Pronostico { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryRegistros { get; set; }
        public Nullable<int> i_MedicoRegistroFinal { get; set; }
    
        public virtual hospitalizacion hospitalizacion { get; set; }
    }
}
