//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospitalizacionNotasEnfermeria
    {
        public string v_HospNotasEnfermeriaId { get; set; }
        public string v_HopitalizacionId { get; set; }
        public string v_NotaEnfermeria { get; set; }
        public string v_MedicacionAlimentacion { get; set; }
        public Nullable<int> i_LicRegistroFinal { get; set; }
        public Nullable<System.DateTime> d_Registro { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryRegistros { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
    
        public virtual hospitalizacion hospitalizacion { get; set; }
    }
}
