//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospitalizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospitalizacion()
        {
            this.hospitalizacionCheckList = new HashSet<hospitalizacionCheckList>();
            this.hospitalizacionEpicrisis = new HashSet<hospitalizacionEpicrisis>();
            this.hospitalizacionIndicacionesMedicas = new HashSet<hospitalizacionIndicacionesMedicas>();
            this.hospitalizacionNotasEnfermeria = new HashSet<hospitalizacionNotasEnfermeria>();
            this.hospitalizacionNotasMedicas = new HashSet<hospitalizacionNotasMedicas>();
            this.hospitalizacionservice = new HashSet<hospitalizacionservice>();
        }
    
        public string v_HopitalizacionId { get; set; }
        public string v_PersonId { get; set; }
        public Nullable<System.DateTime> d_FechaIngreso { get; set; }
        public Nullable<System.DateTime> d_FechaAlta { get; set; }
        public string v_Comentario { get; set; }
        public string v_NroLiquidacion { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<decimal> d_PagoMedico { get; set; }
        public Nullable<int> i_MedicoPago { get; set; }
        public Nullable<decimal> d_PagoPaciente { get; set; }
        public Nullable<int> i_PacientePago { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public string v_DiseasesName { get; set; }
        public string v_CIE10Id { get; set; }
        public string v_ProcedenciaPac { get; set; }
        public string v_Comprobantes { get; set; }
        public Nullable<decimal> d_MontoPagado { get; set; }
        public Nullable<int> i_PasoSop { get; set; }
        public Nullable<int> i_PasoHosp { get; set; }
        public string v_DiseasesNameSalida { get; set; }
        public string v_CIE10IdSalida { get; set; }
        public string v_FechaHoraInicioSop { get; set; }
        public string v_FechaHoraFinSop { get; set; }
        public Nullable<System.DateTime> d_FechaHoraInicioSop { get; set; }
        public Nullable<System.DateTime> d_FechaHoraFinSop { get; set; }
        public Nullable<int> i_TramaHosp { get; set; }
        public Nullable<int> i_TramaSop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospitalizacionCheckList> hospitalizacionCheckList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospitalizacionEpicrisis> hospitalizacionEpicrisis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospitalizacionIndicacionesMedicas> hospitalizacionIndicacionesMedicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospitalizacionNotasEnfermeria> hospitalizacionNotasEnfermeria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospitalizacionNotasMedicas> hospitalizacionNotasMedicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hospitalizacionservice> hospitalizacionservice { get; set; }
    }
}
