//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospitalizacionhabitacion
    {
        public string v_HospitalizacionHabitacionId { get; set; }
        public string v_HopitalizacionId { get; set; }
        public Nullable<int> i_HabitacionId { get; set; }
        public Nullable<System.DateTime> d_StartDate { get; set; }
        public Nullable<System.DateTime> d_EndDate { get; set; }
        public Nullable<decimal> d_Precio { get; set; }
        public Nullable<int> i_ConCargoA { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<decimal> d_SaldoPaciente { get; set; }
        public Nullable<decimal> d_SaldoAseguradora { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public Nullable<int> i_EstateRoom { get; set; }
    }
}
