//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class inmunizaciones
    {
        public string v_VacunacionId { get; set; }
        public string v_PersonId { get; set; }
        public Nullable<int> i_TipoVacuna { get; set; }
        public Nullable<int> i_Marca { get; set; }
        public string v_Lote { get; set; }
        public Nullable<System.DateTime> d_FechaVacuna { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public Nullable<int> i_Dosis { get; set; }
        public string v_Lugar { get; set; }
    
        public virtual person person { get; set; }
    }
}
