//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratorio
    {
        public string v_LaboratorioId { get; set; }
        public string v_ServicioId { get; set; }
        public string v_Hemoglobina { get; set; }
        public string v_Hematocrito { get; set; }
        public string v_NeutrofilosSegementados { get; set; }
        public string v_Abastonados { get; set; }
        public string v_Segmentados { get; set; }
        public string v_Monocitos { get; set; }
        public string v_Eosinofilos { get; set; }
        public string v_Basofilos { get; set; }
        public string v_Linfocitos { get; set; }
        public string v_Hematies { get; set; }
        public string v_Plaquetas { get; set; }
        public string v_Mielocitos { get; set; }
        public string v_Juveniles { get; set; }
        public string v_Glucosa { get; set; }
        public string v_ColesterolTotal { get; set; }
        public string v_ColesterolHDL { get; set; }
        public string v_ColesterolLDL { get; set; }
        public string v_VLDL { get; set; }
        public string v_Trigliceridos { get; set; }
        public string v_TGO { get; set; }
        public string v_TGP { get; set; }
        public string v_CreatininaSuero { get; set; }
        public string v_Color { get; set; }
        public string v_Aspecto { get; set; }
        public string v_Densidad { get; set; }
        public string v_ReaccionPH { get; set; }
        public string v_GlucosaExamenCompletoOrina { get; set; }
        public string v_Bilirrubinas { get; set; }
        public string v_Cetonas { get; set; }
        public string v_ProteinasTotales { get; set; }
        public string v_Urobilinogeno { get; set; }
        public string v_Leucocitos { get; set; }
        public string v_Hematies_ { get; set; }
        public string v_Levaduras { get; set; }
        public string v_CristDeoxalatosCalcio { get; set; }
        public string v_Germenes { get; set; }
        public string v_Albumina { get; set; }
        public string v_LeucocitosTotales { get; set; }
        public string v_Piocitos { get; set; }
        public string v_FilamentosMucoides { get; set; }
        public string v_CCVolumenCorpuscularMedio { get; set; }
        public string v_CCHBCorpuscular { get; set; }
        public string v_LuesVDRL { get; set; }
        public string v_PlomoSangre { get; set; }
        public string v_Magnesio { get; set; }
        public string v_Cocaina { get; set; }
        public string v_Marihuana { get; set; }
        public Nullable<System.DateTime> d_FechaInsercion { get; set; }
        public Nullable<int> i_UsuarioInsertaId { get; set; }
        public Nullable<System.DateTime> d_FechaActualizacion { get; set; }
        public Nullable<int> i_UsuarioActualizaId { get; set; }
        public Nullable<bool> i_EsEliminado { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
