//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class liquidacion
    {
        public string v_LiquidacionId { get; set; }
        public string v_NroLiquidacion { get; set; }
        public string v_OrganizationId { get; set; }
        public Nullable<decimal> d_Monto { get; set; }
        public Nullable<System.DateTime> d_FechaVencimiento { get; set; }
        public string v_NroFactura { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ServiceId { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual organization organization { get; set; }
    }
}
