//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public string v_LogId { get; set; }
        public Nullable<int> i_NodeLogId { get; set; }
        public Nullable<int> i_EventTypeId { get; set; }
        public string v_OrganizationId { get; set; }
        public Nullable<System.DateTime> d_Date { get; set; }
        public Nullable<int> i_SystemUserId { get; set; }
        public string v_ProcessEntity { get; set; }
        public string v_ElementItem { get; set; }
        public Nullable<int> i_Success { get; set; }
        public string v_ErrorException { get; set; }
        public string v_ComentaryUpdate { get; set; }
    }
}
