//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class markings
    {
        public int i_DialingId { get; set; }
        public string v_PersonId { get; set; }
        public Nullable<System.DateTime> d_DialingDate { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_TypeMarking { get; set; }
        public Nullable<int> i_PaidOut { get; set; }
        public Nullable<System.TimeSpan> t_ExtraHours { get; set; }
        public Nullable<System.TimeSpan> t_HoursAgainst { get; set; }
        public string v_ScheduleDetailId { get; set; }
    }
}
