//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicina
    {
        public string v_MedicinaId { get; set; }
        public string v_ServicioId { get; set; }
        public string v_Cabeza { get; set; }
        public string v_Cuello { get; set; }
        public string v_Nariz { get; set; }
        public string v_BocaAmigdalas { get; set; }
        public string v_MiembrosSuperiores { get; set; }
        public string v_MiembrosInferiores { get; set; }
        public string v_ReflejosOsteos { get; set; }
        public string v_Columna { get; set; }
        public string v_EnMarcha { get; set; }
        public string v_Abdomen { get; set; }
        public string v_DesGeneral { get; set; }
        public string v_Anillos { get; set; }
        public string v_Hernias { get; set; }
        public string v_Varices { get; set; }
        public string v_Genitales { get; set; }
        public string v_Ganglios { get; set; }
        public string v_LenguajeAtencionMemoria { get; set; }
        public string v_ConclusionesMedicina { get; set; }
        public Nullable<System.DateTime> d_FechaInsercion { get; set; }
        public Nullable<int> i_UsuarioInsertaId { get; set; }
        public Nullable<System.DateTime> d_FechaActualizacion { get; set; }
        public Nullable<int> i_UsuarioActualizaId { get; set; }
        public Nullable<bool> i_EsEliminado { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
