//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class medication
    {
        public string v_MedicationId { get; set; }
        public string v_ServiceId { get; set; }
        public string v_ProductId { get; set; }
        public string v_ProductName { get; set; }
        public string v_PresentationName { get; set; }
        public Nullable<float> r_Quantity { get; set; }
        public Nullable<float> r_QuantityVendida { get; set; }
        public string v_Doses { get; set; }
        public Nullable<int> i_ViaId { get; set; }
        public Nullable<int> i_SeVendio { get; set; }
        public Nullable<int> i_SeCreoAca { get; set; }
        public string v_TipoDocVenta { get; set; }
        public string v_NroDocVenta { get; set; }
        public Nullable<decimal> d_PrecioVenta { get; set; }
        public string v_MedioPago { get; set; }
        public string v_Vendedor { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual service service { get; set; }
    }
}
