//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class medico
    {
        public string v_MedicoId { get; set; }
        public Nullable<int> i_MasterServiceId { get; set; }
        public Nullable<int> i_SystemUserId { get; set; }
        public Nullable<int> i_MasterServiceTypeId { get; set; }
        public Nullable<decimal> r_Clinica { get; set; }
        public Nullable<decimal> r_Medico { get; set; }
        public Nullable<int> i_CategoryId { get; set; }
        public Nullable<decimal> r_Price { get; set; }
        public string v_EmployerOrganizationId { get; set; }
        public string v_CustomerOrganizationId { get; set; }
        public string v_WorkingOrganizationId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
    }
}
