//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class menssge
    {
        public int i_smsId { get; set; }
        public Nullable<int> v_phoneNummber { get; set; }
        public string v_smsContent { get; set; }
        public Nullable<int> i_status { get; set; }
        public string v_componentName { get; set; }
        public string v_ProtocolName { get; set; }
        public string v_smsContent2 { get; set; }
        public string v_NameClient { get; set; }
        public string v_user { get; set; }
        public string v_pass { get; set; }
    }
}
