//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class movement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movement()
        {
            this.movementdetail = new HashSet<movementdetail>();
        }
    
        public string v_MovementId { get; set; }
        public string v_WarehouseId { get; set; }
        public string v_SupplierId { get; set; }
        public Nullable<int> i_ProcessTypeId { get; set; }
        public string v_ParentMovementId { get; set; }
        public string v_Motive { get; set; }
        public Nullable<int> i_MotiveTypeId { get; set; }
        public Nullable<System.DateTime> d_Date { get; set; }
        public Nullable<float> r_TotalQuantity { get; set; }
        public Nullable<int> i_MovementTypeId { get; set; }
        public Nullable<int> i_RequireRemoteProcess { get; set; }
        public string v_RemoteWarehouseId { get; set; }
        public Nullable<int> i_CurrencyId { get; set; }
        public Nullable<float> r_ExchangeRate { get; set; }
        public string v_ReferenceDocument { get; set; }
        public Nullable<int> i_CostCenterId { get; set; }
        public string v_Observations { get; set; }
        public Nullable<int> i_IsLocallyProcessed { get; set; }
        public Nullable<int> i_IsRemoteProcessed { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_UpdateNodeId { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movementdetail> movementdetail { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
