//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class movementdetail
    {
        public string v_MovementId { get; set; }
        public string v_ProductId { get; set; }
        public string v_WarehouseId { get; set; }
        public Nullable<float> r_StockMax { get; set; }
        public Nullable<float> r_StockMin { get; set; }
        public Nullable<int> i_MovementTypeId { get; set; }
        public Nullable<float> r_Quantity { get; set; }
        public Nullable<float> r_Price { get; set; }
        public Nullable<float> r_SubTotal { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
    
        public virtual movement movement { get; set; }
        public virtual product product { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
