//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public node()
        {
            this.attentioninarea = new HashSet<attentioninarea>();
            this.nodeorganizationlocationprofile = new HashSet<nodeorganizationlocationprofile>();
            this.nodeorganizationlocationwarehouseprofile = new HashSet<nodeorganizationlocationwarehouseprofile>();
            this.nodeserviceprofile = new HashSet<nodeserviceprofile>();
            this.nodeorganizationprofile = new HashSet<nodeorganizationprofile>();
            this.rolenode = new HashSet<rolenode>();
        }
    
        public int i_NodeId { get; set; }
        public string v_Description { get; set; }
        public string v_GeografyLocationId { get; set; }
        public string v_GeografyLocationDescription { get; set; }
        public Nullable<int> i_NodeTypeId { get; set; }
        public Nullable<System.DateTime> d_BeginDate { get; set; }
        public Nullable<System.DateTime> d_EndDate { get; set; }
        public string v_PharmacyWarehouseId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attentioninarea> attentioninarea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nodeorganizationlocationprofile> nodeorganizationlocationprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nodeorganizationlocationwarehouseprofile> nodeorganizationlocationwarehouseprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nodeserviceprofile> nodeserviceprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nodeorganizationprofile> nodeorganizationprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rolenode> rolenode { get; set; }
    }
}
