//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class nodesyncstatus
    {
        public int i_NodeId { get; set; }
        public string v_DataSyncVersion { get; set; }
        public Nullable<int> i_DataSyncFrecuency { get; set; }
        public Nullable<System.DateTime> d_LastSuccessfulDataSync { get; set; }
        public Nullable<int> i_LastServerProcessStatus { get; set; }
        public Nullable<int> i_LastNodeProcessStatus { get; set; }
        public Nullable<System.DateTime> d_NextDataSync { get; set; }
        public string v_LastServerPackageFileName { get; set; }
        public string v_LastServerProcessErrorMessage { get; set; }
        public string v_LastNodePackageFileName { get; set; }
        public string v_LastNodeProcessErrorMessage { get; set; }
        public string v_ComentaryUpdate { get; set; }
    }
}
