//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public string v_NotificationId { get; set; }
        public string v_OrganizationId { get; set; }
        public Nullable<System.DateTime> d_NotificationDate { get; set; }
        public string v_PersonId { get; set; }
        public string v_Title { get; set; }
        public string v_Body { get; set; }
        public Nullable<int> i_IsRead { get; set; }
        public Nullable<int> i_TypeNotificationId { get; set; }
        public Nullable<System.DateTime> d_ScheduleDate { get; set; }
        public Nullable<int> i_StateNotificationId { get; set; }
        public string v_Path { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
    }
}
