//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oftalmologia
    {
        public string v_OftalmologiaId { get; set; }
        public string v_ServicioId { get; set; }
        public string v_vcscOD { get; set; }
        public string v_vcscOI { get; set; }
        public string v_vcccOD { get; set; }
        public string v_vcccOI { get; set; }
        public string v_vlscOD { get; set; }
        public string v_vlscOI { get; set; }
        public string v_vlccOD { get; set; }
        public string v_vlccOI { get; set; }
        public string v_VisionColores { get; set; }
        public string v_EnfermedadesOculares { get; set; }
        public string v_ReflejosPupilares { get; set; }
        public string v_ConclusionesOftalmologia { get; set; }
        public Nullable<System.DateTime> d_FechaInsercion { get; set; }
        public Nullable<int> i_UsuarioInsertaId { get; set; }
        public Nullable<System.DateTime> d_FechaActualizacion { get; set; }
        public Nullable<int> i_UsuarioActualizaId { get; set; }
        public Nullable<bool> i_EsEliminado { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
