//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenReporte
    {
        public string v_OrdenReporteId { get; set; }
        public string v_OrganizationId { get; set; }
        public string v_NombreReporte { get; set; }
        public string v_ComponenteId { get; set; }
        public Nullable<int> i_Orden { get; set; }
        public string v_NombreCrystal { get; set; }
        public Nullable<int> i_NombreCrystalId { get; set; }
        public string v_ComentaryUpdate { get; set; }
    }
}
