//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organization()
        {
            this.liquidacion = new HashSet<liquidacion>();
            this.location = new HashSet<location>();
            this.nodeorganizationlocationprofile = new HashSet<nodeorganizationlocationprofile>();
            this.nodeorganizationlocationwarehouseprofile = new HashSet<nodeorganizationlocationwarehouseprofile>();
            this.nodeorganizationprofile = new HashSet<nodeorganizationprofile>();
            this.warehouse = new HashSet<warehouse>();
        }
    
        public string v_OrganizationId { get; set; }
        public Nullable<int> i_OrganizationTypeId { get; set; }
        public Nullable<int> i_SectorTypeId { get; set; }
        public string v_SectorName { get; set; }
        public string v_SectorCodigo { get; set; }
        public string v_IdentificationNumber { get; set; }
        public string v_Name { get; set; }
        public string v_Address { get; set; }
        public string v_PhoneNumber { get; set; }
        public string v_Mail { get; set; }
        public string v_ContacName { get; set; }
        public string v_Contacto { get; set; }
        public string v_EmailContacto { get; set; }
        public string v_Observation { get; set; }
        public Nullable<int> i_NumberQuotasOrganization { get; set; }
        public Nullable<int> i_NumberQuotasMen { get; set; }
        public Nullable<int> i_NumberQuotasWomen { get; set; }
        public Nullable<int> i_DepartmentId { get; set; }
        public Nullable<int> i_ProvinceId { get; set; }
        public Nullable<int> i_DistrictId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public byte[] b_Image { get; set; }
        public string v_ContactoMedico { get; set; }
        public string v_EmailMedico { get; set; }
        public Nullable<decimal> r_Factor { get; set; }
        public Nullable<decimal> r_FactorMed { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<liquidacion> liquidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<location> location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nodeorganizationlocationprofile> nodeorganizationlocationprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nodeorganizationlocationwarehouseprofile> nodeorganizationlocationwarehouseprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nodeorganizationprofile> nodeorganizationprofile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouse> warehouse { get; set; }
    }
}
