//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.AlergiasInmunizaciones = new HashSet<AlergiasInmunizaciones>();
            this.Antecedentes = new HashSet<Antecedentes>();
            this.Habitos = new HashSet<Habitos>();
            this.Servicio = new HashSet<Servicio>();
        }
    
        public string v_PersonaId { get; set; }
        public string v_Apellidos { get; set; }
        public string v_Nombres { get; set; }
        public string v_DocNumero { get; set; }
        public Nullable<System.DateTime> d_FechNac { get; set; }
        public string v_NumeroTelefono { get; set; }
        public Nullable<int> i_TipoSexo { get; set; }
        public Nullable<int> i_EstadoCivil { get; set; }
        public Nullable<int> i_GradoInstruccion { get; set; }
        public Nullable<int> i_GrupoSanguineo { get; set; }
        public Nullable<int> i_FactorSanguineo { get; set; }
        public Nullable<int> i_Distrito { get; set; }
        public Nullable<int> i_Provincia { get; set; }
        public Nullable<int> i_Departamento { get; set; }
        public Nullable<int> i_NumHijosVivos { get; set; }
        public Nullable<System.DateTime> d_FechaInsercion { get; set; }
        public Nullable<int> i_UsuarioInsertaId { get; set; }
        public Nullable<System.DateTime> d_FechaActualizacion { get; set; }
        public Nullable<int> i_UsuarioActualizaId { get; set; }
        public Nullable<bool> i_EsEliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlergiasInmunizaciones> AlergiasInmunizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antecedentes> Antecedentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitos> Habitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio> Servicio { get; set; }
    }
}
