//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.adolescente = new HashSet<adolescente>();
            this.adulto = new HashSet<adulto>();
            this.adultomayor = new HashSet<adultomayor>();
            this.blacklistperson = new HashSet<blacklistperson>();
            this.calendar = new HashSet<calendar>();
            this.DigitalContactCenter = new HashSet<DigitalContactCenter>();
            this.embarzo = new HashSet<embarzo>();
            this.familymedicalantecedents = new HashSet<familymedicalantecedents>();
            this.history = new HashSet<history>();
            this.HojaReclamo = new HashSet<HojaReclamo>();
            this.inmunizaciones = new HashSet<inmunizaciones>();
            this.multimediafile = new HashSet<multimediafile>();
            this.Ninio = new HashSet<Ninio>();
            this.noxioushabits = new HashSet<noxioushabits>();
            this.personmedicalhistory = new HashSet<personmedicalhistory>();
            this.service = new HashSet<service>();
            this.systemuser = new HashSet<systemuser>();
            this.vigilancia = new HashSet<vigilancia>();
        }
    
        public string v_PersonId { get; set; }
        public string v_FirstName { get; set; }
        public string v_FirstLastName { get; set; }
        public string v_SecondLastName { get; set; }
        public Nullable<int> i_DocTypeId { get; set; }
        public string v_DocNumber { get; set; }
        public Nullable<System.DateTime> d_Birthdate { get; set; }
        public string v_BirthPlace { get; set; }
        public Nullable<int> i_SexTypeId { get; set; }
        public Nullable<int> i_MaritalStatusId { get; set; }
        public Nullable<int> i_LevelOfId { get; set; }
        public string v_TelephoneNumber { get; set; }
        public string v_AdressLocation { get; set; }
        public string v_GeografyLocationId { get; set; }
        public string v_ContactName { get; set; }
        public string v_EmergencyPhone { get; set; }
        public byte[] b_PersonImage { get; set; }
        public string v_Mail { get; set; }
        public Nullable<int> i_BloodGroupId { get; set; }
        public Nullable<int> i_BloodFactorId { get; set; }
        public byte[] b_FingerPrintTemplate { get; set; }
        public byte[] b_RubricImage { get; set; }
        public byte[] b_FingerPrintImage { get; set; }
        public string t_RubricImageText { get; set; }
        public string v_CurrentOccupation { get; set; }
        public Nullable<int> i_DepartmentId { get; set; }
        public Nullable<int> i_ProvinceId { get; set; }
        public Nullable<int> i_DistrictId { get; set; }
        public Nullable<int> i_ResidenceInWorkplaceId { get; set; }
        public string v_ResidenceTimeInWorkplace { get; set; }
        public Nullable<int> i_TypeOfInsuranceId { get; set; }
        public Nullable<int> i_NumberLivingChildren { get; set; }
        public Nullable<int> i_NumberDependentChildren { get; set; }
        public Nullable<int> i_OccupationTypeId { get; set; }
        public string v_OwnerName { get; set; }
        public Nullable<int> i_NumberLiveChildren { get; set; }
        public Nullable<int> i_NumberDeadChildren { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_InsertNodeId { get; set; }
        public Nullable<int> i_UpdateNodeId { get; set; }
        public Nullable<int> i_Relationship { get; set; }
        public string v_ExploitedMineral { get; set; }
        public Nullable<int> i_AltitudeWorkId { get; set; }
        public Nullable<int> i_PlaceWorkId { get; set; }
        public string v_NroPoliza { get; set; }
        public Nullable<decimal> v_Deducible { get; set; }
        public Nullable<int> i_NroHermanos { get; set; }
        public string v_Password { get; set; }
        public string v_Procedencia { get; set; }
        public string v_CentroEducativo { get; set; }
        public string v_Religion { get; set; }
        public string v_Nacionalidad { get; set; }
        public string v_ResidenciaAnterior { get; set; }
        public string v_Subs { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public string v_PhoneContac { get; set; }
        public Nullable<int> i_Marketing { get; set; }
        public string v_ProtocolId { get; set; }
        public Nullable<System.DateTime> d_ExpirationDate { get; set; }
        public Nullable<int> i_TotalAtenciones { get; set; }
        public Nullable<int> i_CountAtenciones { get; set; }
        public Nullable<int> i_EtniaRaza { get; set; }
        public Nullable<int> i_Migrante { get; set; }
        public string v_Migrante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adolescente> adolescente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adulto> adulto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adultomayor> adultomayor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blacklistperson> blacklistperson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<calendar> calendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DigitalContactCenter> DigitalContactCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<embarzo> embarzo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<familymedicalantecedents> familymedicalantecedents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<history> history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HojaReclamo> HojaReclamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inmunizaciones> inmunizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<multimediafile> multimediafile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ninio> Ninio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<noxioushabits> noxioushabits { get; set; }
        public virtual pacient pacient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personmedicalhistory> personmedicalhistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<systemuser> systemuser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vigilancia> vigilancia { get; set; }
        public virtual professional professional { get; set; }
    }
}
