//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsformigration
    {
        public int i_ProductForMigrationId { get; set; }
        public string v_WarehouseId { get; set; }
        public string v_ProductId { get; set; }
        public Nullable<int> i_CategoryId { get; set; }
        public string v_Name { get; set; }
        public Nullable<float> r_StockMin { get; set; }
        public Nullable<float> r_StockMax { get; set; }
        public Nullable<float> r_StockActual { get; set; }
        public Nullable<int> i_MovementTypeId { get; set; }
        public string v_MovementType { get; set; }
        public Nullable<int> i_MotiveTypeId { get; set; }
        public string v_MotiveType { get; set; }
        public Nullable<System.DateTime> d_MovementDate { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
    }
}
