//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class professional
    {
        public string v_PersonId { get; set; }
        public Nullable<int> i_ProfessionId { get; set; }
        public string v_ProfessionalCode { get; set; }
        public string v_ProfessionalInformation { get; set; }
        public byte[] b_SignatureImage { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_UpdateNodeId { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public string v_ComponentId { get; set; }
        public Nullable<decimal> r_MonthlyPayment { get; set; }
        public Nullable<System.TimeSpan> t_MonthlyHours { get; set; }
        public Nullable<System.DateTime> d_StartDateOfWork { get; set; }
        public Nullable<System.DateTime> d_ContractFrom { get; set; }
        public Nullable<System.DateTime> d_ContractUntil { get; set; }
        public Nullable<System.DateTime> d_CessationDate { get; set; }
        public Nullable<int> i_Profesion { get; set; }
        public Nullable<int> i_Profesion2 { get; set; }
        public Nullable<int> i_GrupoHorario { get; set; }
        public Nullable<int> i_CodigoProfesion { get; set; }
    
        public virtual person person { get; set; }
    }
}
