//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class protocol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public protocol()
        {
            this.protocolcomponent = new HashSet<protocolcomponent>();
            this.protocolsystemuser = new HashSet<protocolsystemuser>();
            this.service = new HashSet<service>();
            this.serviceorderdetail = new HashSet<serviceorderdetail>();
        }
    
        public string v_ProtocolId { get; set; }
        public string v_Name { get; set; }
        public string v_EmployerOrganizationId { get; set; }
        public string v_EmployerLocationId { get; set; }
        public Nullable<int> i_EsoTypeId { get; set; }
        public string v_GroupOccupationId { get; set; }
        public string v_CustomerOrganizationId { get; set; }
        public string v_CustomerLocationId { get; set; }
        public string v_NombreVendedor { get; set; }
        public string v_WorkingOrganizationId { get; set; }
        public string v_WorkingLocationId { get; set; }
        public string v_CostCenter { get; set; }
        public Nullable<int> i_MasterServiceTypeId { get; set; }
        public Nullable<int> i_MasterServiceId { get; set; }
        public Nullable<int> i_HasVigency { get; set; }
        public Nullable<int> i_ValidInDays { get; set; }
        public Nullable<int> i_IsActive { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_AseguradoraOrganizationId { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public Nullable<double> r_PriceFactor { get; set; }
        public Nullable<double> r_MedicineDiscount { get; set; }
        public Nullable<double> r_HospitalBedPrice { get; set; }
        public Nullable<double> r_ClinicDiscount { get; set; }
        public Nullable<double> r_DiscountExam { get; set; }
        public Nullable<int> i_Consultorio { get; set; }
        public string v_Procedencia { get; set; }
        public Nullable<decimal> d_PrecioConsulta { get; set; }
        public Nullable<decimal> d_DescuentoLaboratorio { get; set; }
        public Nullable<decimal> d_DescuentoRayosX { get; set; }
        public Nullable<decimal> d_DescuentoEcografias { get; set; }
        public Nullable<decimal> d_DescuentoFarmacia { get; set; }
        public Nullable<decimal> d_DescuentoOdontologia { get; set; }
        public Nullable<decimal> d_CamaHosp { get; set; }
        public Nullable<decimal> d_SalaOperaciones { get; set; }
        public Nullable<decimal> d_PrecioAmbulancia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<protocolcomponent> protocolcomponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<protocolsystemuser> protocolsystemuser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service> service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviceorderdetail> serviceorderdetail { get; set; }
    }
}
