//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RayosX
    {
        public string v_RayosXId { get; set; }
        public string v_ServicioId { get; set; }
        public string v_0 { get; set; }
        public string v_0_0 { get; set; }
        public string v_0_1 { get; set; }
        public string v_1_0 { get; set; }
        public string v_1_1 { get; set; }
        public string v_1_2 { get; set; }
        public string v_2_1 { get; set; }
        public string v_2_2 { get; set; }
        public string v_2_3 { get; set; }
        public string v_3_1 { get; set; }
        public string v_3_2 { get; set; }
        public string v_3_ { get; set; }
        public string v_ConclusionesRayosX { get; set; }
        public Nullable<System.DateTime> d_FechaInsercion { get; set; }
        public Nullable<int> i_UsuarioInsertaId { get; set; }
        public Nullable<System.DateTime> d_FechaActualizacion { get; set; }
        public Nullable<int> i_UsuarioActualizaId { get; set; }
        public Nullable<bool> i_EsEliminado { get; set; }
    
        public virtual Servicio Servicio { get; set; }
    }
}
