//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta
    {
        public int i_IdReceta { get; set; }
        public string v_DiagnosticRepositoryId { get; set; }
        public Nullable<decimal> d_Cantidad { get; set; }
        public string v_Posologia { get; set; }
        public string v_Duracion { get; set; }
        public Nullable<System.DateTime> t_FechaFin { get; set; }
        public string v_IdProductoDetalle { get; set; }
        public string v_Lote { get; set; }
        public Nullable<int> i_IdAlmacen { get; set; }
        public Nullable<int> i_Lleva { get; set; }
        public Nullable<int> i_NoLleva { get; set; }
        public string v_IdVentaPaciente { get; set; }
        public string v_IdVentaAseguradora { get; set; }
        public string v_IdUnidadProductiva { get; set; }
        public Nullable<decimal> d_SaldoPaciente { get; set; }
        public Nullable<decimal> d_SaldoAseguradora { get; set; }
        public string v_ServiceId { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public string v_Comprobante { get; set; }
        public Nullable<int> v_MedicoTratante { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_PayMedic { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public string v_ReceipId { get; set; }
    }
}
