//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class restriction
    {
        public string v_RestrictionId { get; set; }
        public string v_DiagnosticRepositoryId { get; set; }
        public string v_ServiceId { get; set; }
        public string v_ComponentId { get; set; }
        public string v_MasterRestrictionId { get; set; }
        public Nullable<System.DateTime> d_StartDateRestriction { get; set; }
        public Nullable<System.DateTime> d_EndDateRestriction { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual component component { get; set; }
        public virtual diagnosticrepository diagnosticrepository { get; set; }
        public virtual service service { get; set; }
    }
}
