//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class secuential
    {
        public int i_NodeId { get; set; }
        public int i_TableId { get; set; }
        public Nullable<int> i_SecuentialId { get; set; }
        public string v_ComentaryUpdate { get; set; }
    }
}
