//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviceorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public serviceorder()
        {
            this.serviceorderdetail = new HashSet<serviceorderdetail>();
        }
    
        public string v_ServiceOrderId { get; set; }
        public string v_CustomServiceOrderId { get; set; }
        public string v_Description { get; set; }
        public string v_Comentary { get; set; }
        public Nullable<int> i_NumberOfWorker { get; set; }
        public Nullable<float> r_TotalCost { get; set; }
        public Nullable<System.DateTime> d_DeliveryDate { get; set; }
        public Nullable<int> i_ServiceOrderStatusId { get; set; }
        public Nullable<int> i_LineaCreditoId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_MostrarPrecio { get; set; }
        public Nullable<int> i_EsProtocoloEspecial { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviceorderdetail> serviceorderdetail { get; set; }
    }
}
