//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicecomponentfieldvalues
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicecomponentfieldvalues()
        {
            this.servicecomponentfieldValuesmultimedia = new HashSet<servicecomponentfieldValuesmultimedia>();
        }
    
        public string v_ServiceComponentFieldValuesId { get; set; }
        public string v_ComponentFieldValuesId { get; set; }
        public string v_ServiceComponentFieldsId { get; set; }
        public string v_Value1 { get; set; }
        public string v_Value2 { get; set; }
        public Nullable<int> i_Index { get; set; }
        public Nullable<int> i_Value1 { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual componentfieldvalues componentfieldvalues { get; set; }
        public virtual servicecomponentfields servicecomponentfields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicecomponentfieldValuesmultimedia> servicecomponentfieldValuesmultimedia { get; set; }
    }
}
