//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicecomponentmultimedia
    {
        public string v_ServiceComponentMultimediaId { get; set; }
        public string v_ServiceComponentId { get; set; }
        public string v_MultimediaFileId { get; set; }
        public string v_Comment { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public string v_Ext { get; set; }
    
        public virtual multimediafile multimediafile { get; set; }
        public virtual servicecomponent servicecomponent { get; set; }
    }
}
