//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceComponentsDownload
    {
        public int i_ServiceComponetsDownloadId { get; set; }
        public string v_ServiceId { get; set; }
        public string v_ComponentName { get; set; }
        public Nullable<int> i_Status { get; set; }
        public string v_ManagerAuthorizeId { get; set; }
        public string v_paymentType { get; set; }
        public string v_TypeDoc { get; set; }
        public string v_NroDoc { get; set; }
        public Nullable<int> i_amount { get; set; }
        public string v_Reference { get; set; }
        public string v_IdInsert { get; set; }
        public Nullable<System.DateTime> d_dateInsert { get; set; }
        public string v_idupdate { get; set; }
        public Nullable<System.DateTime> d_update { get; set; }
        public Nullable<System.DateTime> d_RequiredUser { get; set; }
        public string v_FileNameDni { get; set; }
        public byte[] b_FileContentDni { get; set; }
        public string v_FileNameDoc { get; set; }
        public byte[] b_FileContentDoc { get; set; }
        public string v_BaucherName { get; set; }
        public byte[] b_BaucherContent { get; set; }
    }
}
