//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms
    {
        public int i_smsId { get; set; }
        public string v_phoneNummber { get; set; }
        public string v_personId { get; set; }
        public string v_smsContent { get; set; }
        public Nullable<int> i_status { get; set; }
        public Nullable<System.DateTime> d_dateSend { get; set; }
        public Nullable<int> i_ServiceComponetsDownloadID { get; set; }
    }
}
