//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class softwarecomponentrelease
    {
        public int i_SoftwareComponentId { get; set; }
        public string v_SoftwareComponentVersion { get; set; }
        public Nullable<int> i_DeploymentFileId { get; set; }
        public Nullable<System.DateTime> d_ReleaseDate { get; set; }
        public string v_DatabaseVersionRequired { get; set; }
        public string v_ReleaseNotes { get; set; }
        public string v_AdditionalInformation1 { get; set; }
        public string v_AdditionalInformation2 { get; set; }
        public Nullable<int> i_IsPublished { get; set; }
        public Nullable<int> i_IsLastVersion { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual deploymentfile deploymentfile { get; set; }
    }
}
