//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemuser
    {
        public int i_SystemUserId { get; set; }
        public string v_PersonId { get; set; }
        public string v_UserName { get; set; }
        public string v_Password { get; set; }
        public string v_SecretQuestion { get; set; }
        public string v_SecretAnswer { get; set; }
        public Nullable<System.DateTime> d_ExpireDate { get; set; }
        public string v_SystemUserByOrganizationId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_SystemUserTypeId { get; set; }
        public Nullable<int> i_RolVentaId { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public Nullable<int> i_LoginFrecuency { get; set; }
    
        public virtual person person { get; set; }
    }
}
