//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracking
    {
        public string v_SeguroId { get; set; }
        public string v_PersonId { get; set; }
        public Nullable<int> i_Agenda { get; set; }
        public Nullable<int> i_CartaGarantia { get; set; }
        public Nullable<int> i_AtencionMedica { get; set; }
        public Nullable<int> i_PreLiquidacion { get; set; }
        public Nullable<int> i_ControlCalidad { get; set; }
        public Nullable<int> i_Facturacion { get; set; }
        public Nullable<int> i_Culminado { get; set; }
        public string v_ServiceId { get; set; }
    }
}
