//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tramas
    {
        public string v_TramaId { get; set; }
        public string v_TipoRegistro { get; set; }
        public Nullable<System.DateTime> d_FechaIngreso { get; set; }
        public Nullable<System.DateTime> d_FechaAlta { get; set; }
        public Nullable<int> i_Genero { get; set; }
        public Nullable<int> i_GrupoEtario { get; set; }
        public string v_DiseasesName { get; set; }
        public string v_CIE10Id { get; set; }
        public Nullable<int> i_UPS { get; set; }
        public Nullable<int> i_Procedimiento { get; set; }
        public Nullable<int> i_Especialidad { get; set; }
        public Nullable<int> i_TipoParto { get; set; }
        public Nullable<int> i_TipoNacimiento { get; set; }
        public Nullable<int> i_TipoComplicacion { get; set; }
        public Nullable<int> i_Programacion { get; set; }
        public Nullable<int> i_TipoCirugia { get; set; }
        public Nullable<int> i_HorasProg { get; set; }
        public Nullable<int> i_HorasEfect { get; set; }
        public Nullable<int> i_HorasActo { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public string v_ComentaryUpdate { get; set; }
        public string v_ServiceId { get; set; }
    }
}
