//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacations
    {
        public string v_VacationId { get; set; }
        public string v_PersonId { get; set; }
        public Nullable<int> i_IsProcessed { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<System.DateTime> d_StartVacation { get; set; }
        public Nullable<System.DateTime> d_EndVacation { get; set; }
    }
}
