//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class workstationdangers
    {
        public string v_WorkstationDangersId { get; set; }
        public string v_HistoryId { get; set; }
        public Nullable<int> i_DangerId { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
        public Nullable<int> i_NoiseSource { get; set; }
        public Nullable<int> i_NoiseLevel { get; set; }
        public string v_TimeOfExposureToNoise { get; set; }
        public string v_ComentaryUpdate { get; set; }
    
        public virtual history history { get; set; }
    }
}
