//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VigmedSO.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class workersscheduledetail
    {
        public string v_ScheduleDetailId { get; set; }
        public string v_ScheduleId { get; set; }
        public string v_PersonId { get; set; }
        public Nullable<System.DateTime> d_Date { get; set; }
        public Nullable<System.TimeSpan> t_StartDate { get; set; }
        public Nullable<System.TimeSpan> t_StartBreak { get; set; }
        public Nullable<System.TimeSpan> t_EndBreak { get; set; }
        public Nullable<System.TimeSpan> t_EndDate { get; set; }
        public Nullable<int> i_IsDeleted { get; set; }
        public Nullable<int> i_InsertUserId { get; set; }
        public Nullable<System.DateTime> d_InsertDate { get; set; }
        public Nullable<int> i_UpdateUserId { get; set; }
        public Nullable<System.DateTime> d_UpdateDate { get; set; }
    }
}
